### ISSUE TITLE
Print statement resets column widths

### ISSUE THREAD

**Issue by sergei3000** [pri22296/beautifultable#15]
Whenever I use `column_widths` to change this parameter for a column and then run `print(table)`, it resets the column's width back to the previous value.
So I have to use `print(table.get_string(recalculate_width=False))` instead of the simple print statement.

**Comment by pri22296** [comment]
@sergei3000 Currently the code for print statement internally calls the `get_string` method as you can see [here](https://github.com/pri22296/beautifultable/blob/faad0e47eaf347eae5c68812a813715426c1ee19/beautifultable/beautifultable.py#L536) with `recalculate_width` set as `True`. I made that decision as a trade-off so that widths could be adjusted automatically with each change made to the table. If you would like to suggest some other alternative which handles all the cases, I'd be happy to make that change or accept a PR. Meanwhile I'd suggest to continue using `print(table.get_string(recalculate_width=False))` for the intended behaviour.
