### ISSUE TITLE
Underscore in data between 2 digits is stripped

### ISSUE THREAD

**Issue by jason1365** [pri22296/beautifultable#63]
See image for debugging data.

table.append_row(['1234', '10-100', '1d 4h']) #all good
table.append_row(['1234_5678', '10-_00', '1d_4h']) #Underscore in first string is stripped. The other 2 instances are not stripped (for whatever reason). Seems to only be underscore between digits in a string.

![image](https://user-images.githubusercontent.com/16825179/57820417-ba6d5480-775a-11e9-924d-81146e3c6dbc.png)

**Comment by pri22296** [comment]
Thanks for the report. This seems to be happening because an underscore can be present between numeric literals in Python versions 3.6+ as per [PEP 515](https://www.python.org/dev/peps/pep-0515/). Now the library by default tries to detect if any strings are infact numeric data. Hence, it is detecting `'1234_5678'` as an integer. You can disable the automatic numerics detection by setting the [`detect_numerics`](https://beautifultable.readthedocs.io/en/latest/source/beautifultable.html#beautifultable.BeautifulTable.detect_numerics) property to `False`.
